apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app-web
  template:
    metadata:
      labels:
        app: budget-app-web
    spec:
      containers:
        - name: budget-app-web
          image: soahilali31/open-flights:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "openf"
            - name: DB_PASSWORD
              value: "openf"
            - name: DB_NAME
              value: "openf_development"
---
apiVersion: v1
kind: Service
metadata:
  name: open-flights-web-service
spec:
  selector:
    app: budget-app-web
  ports:
    - protocol: TCP
      port: 3000  # Use a specific port for NodePort
      targetPort: 3000
  type: NodePort
