apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
     containers:
        - name: rails
          image: open-flights:latest
          env:
            - name: DATABASE_URL
              value: postgres://openflights:openflights@postgres:5432/openflights
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  selector:
    app: rails
  ports:
    - name: rails
      port: 3000
      targetPort: 3000
  type: LoadBalancer
