apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: your-pipeline-run
spec:
  pipelineRef:
    name: docker-build-and-push-pipeline
  params:
    - name: repo-url
      value: 'https://github.com/sohailali31/open-flights.git'
    - name: repo-revision
      value: 'main'
    - name: image-name
      value: 'open-flights'
    - name: docker-hub-username
      value: 'open-flights'
